import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";



import Header from "@/components/frontend/header/Header";
import Footer from "@/components/frontend/footer/Footer";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
